spring:
  application:
    name: gateway
  cache:
    type: ehcache
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug



