spring:
  application:
    name: dubbo-consumer-demo
server:
  port: 9999
hello:
  service:
    version: 1.0.0
dubbo:
  application:
    id: dubbo-consumer-demo-id
    name: dubbo-consumer-demo-name
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
    id: hello-provider
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'