server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/erueka
  instance:
    hostname: localhost
  server:
    #再没有熔断机制情况下  放弃ap 保证cp
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 120000

